### ISSUE TITLE
AttributeError: 'JsonResponse' object has no attribute '_headers'

### ISSUE THREAD

**Issue by Wissperwind** [Rhumbix/django-request-logging#130]
```
Internal Server Error: /backend/api/sysInfo
Traceback (most recent call last):
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\request_logging\middleware.py", line 106, in __call__
    self.process_response( request, response )
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\request_logging\middleware.py", line 207, in process_response
    self._log_resp(self.log_level, response, logging_context)
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\request_logging\middleware.py", line 254, in _log_resp
    self.logger.log(level, response._headers, logging_context)
AttributeError: 'JsonResponse' object has no attribute '_headers'
```

Is this because Django 3.2 or rest_framework?

**Comment by satori-hmoreau** [comment]
I'm looking at this problem too.  It's definitely to do with rest framework, because the error happens when logging response with content type application/json.  I am using django 3.1.7 and djangorestframework 3.12.2

**Comment by andreparames** [comment]
Django 3.2 changed it from `_headers` to `headers`: https://github.com/django/django/pull/13186/files#diff-ab65c832cdbc45bbac4b1754d569d8f0f353d2ac97b82898b7ec23066cce212bL43

@sgelis did you manage to get it working on 3.2? Maybe we could collaborate on the upgrade, since the repo maintainers seem to be busy?

**Comment by livcarman** [comment]
AFAIK this repo is unmaintained -- you all might be better off creating a fork. The person at Rhumbix who used to maintain this repo no longer works there and as far as I can tell no one at Rhumbix has taken over this project in the year or so since I left the company. I think it's safe to consider this package abandonware at this point.

**Comment by joshua-davis-rose** [comment]
@livcarman is correct. We haven't had the time to give this project the attention it deserves. If anyone is interested in becoming a contributor/maintainer, please let me know.

**Comment by Wissperwind** [comment]
If someone forked it and fixes it, please letzten me know.

**Comment by sgelis** [comment]
@andreparames I have the PR ready, just awaiting for a previous PR (fixing tests) to be merged.

@joshua-davis-rose I would definitely be willing to maintain this package that is so useful to us.

**Comment by andreparames** [comment]
Thanks @livcarman @joshua-davis-rose for the heads up! 

Thanks for offering @sgelis. I can't commit to it in the long term, but I'm ready to help now if you need it 🙂

**Comment by famousfilm** [comment]
resolved by https://github.com/Rhumbix/django-request-logging/pull/132
